"""The two shapes of an extraction.

`RawExtraction` is what a tier returns (a model, or the reader of an embedded e-invoice):
every value is a string, copied as printed. `Invoice` is its normalised form, produced
by `countersign.pipeline.normalise` with deterministic code. Keeping the two apart
means a model is never trusted with a number format, a date convention or a sum.
"""

from datetime import date
from decimal import Decimal
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, model_validator

DocumentType = Literal["invoice", "credit_note", "other"]


_BLANK = frozenset({"", "null", "none", "n/a", "na", "-", "--"})


class _Raw(BaseModel):
    # Tolerate unknown keys: a model that adds one has not made the known ones wrong.
    # A tier may also return numbers as JSON numbers: they are kept as their text.
    model_config = ConfigDict(extra="ignore", str_strip_whitespace=True, coerce_numbers_to_str=True)

    @model_validator(mode="before")
    @classmethod
    def _blank_is_absent(cls, data: Any) -> Any:
        """A model sometimes writes "" or "N/A" where the schema allows null."""
        if not isinstance(data, dict):
            return data
        return {
            key: None if isinstance(value, str) and value.strip().lower() in _BLANK else value
            for key, value in data.items()
        }


class RawLine(_Raw):
    description: str | None = None
    quantity: str | None = None
    unit_price: str | None = None
    amount: str | None = None
    vat_rate: str | None = None


class RawVatLine(_Raw):
    rate: str | None = None
    base: str | None = None
    tax: str | None = None


class RawExtraction(_Raw):
    document_type: DocumentType = "other"
    invoice_number: str | None = None
    issue_date: str | None = None
    due_date: str | None = None
    currency: str | None = None
    supplier_name: str | None = None
    supplier_vat_id: str | None = None
    supplier_siret: str | None = None
    supplier_iban: str | None = None
    po_number: str | None = None
    # On a credit note, the invoice it cancels. Asking for it gives the model somewhere
    # to put that number other than the credit note's own.
    referenced_invoice: str | None = None
    lines: list[RawLine] = []
    allowance_total: str | None = None
    charge_total: str | None = None
    total_net: str | None = None
    vat_breakdown: list[RawVatLine] = []
    total_tax: str | None = None
    total_gross: str | None = None


class Line(BaseModel):
    description: str
    quantity: Decimal | None = None
    unit_price: Decimal | None = None
    amount: Decimal | None = None
    vat_rate: Decimal | None = None


class VatLine(BaseModel):
    rate: Decimal | None = None
    base: Decimal | None = None
    tax: Decimal | None = None


class Invoice(BaseModel):
    """A normalised invoice. Amounts keep the sign printed on the document."""

    document_type: DocumentType = "other"
    invoice_number: str | None = None
    issue_date: date | None = None
    due_date: date | None = None
    currency: str | None = None
    supplier_name: str | None = None
    supplier_vat_id: str | None = None
    supplier_siret: str | None = None
    supplier_iban: str | None = None
    po_number: str | None = None
    referenced_invoice: str | None = None
    lines: list[Line] = []
    allowance_total: Decimal | None = None
    charge_total: Decimal | None = None
    total_net: Decimal | None = None
    vat_breakdown: list[VatLine] = []
    total_tax: Decimal | None = None
    total_gross: Decimal | None = None


# Header fields that decide what gets posted and paid. An automatic approval with one of
# them wrong is the failure this system exists to prevent.
CRITICAL_FIELDS: tuple[str, ...] = (
    "document_type",
    "invoice_number",
    "issue_date",
    "due_date",
    "currency",
    "supplier_vat_id",
    "supplier_iban",
    "po_number",
    "total_net",
    "total_tax",
    "total_gross",
)

_NULLABLE_STRING: dict[str, Any] = {"type": ["string", "null"]}
_NULLABLE_NUMBER: dict[str, Any] = {"type": ["number", "null"]}

NumericFields = Literal["text", "number"]


def extraction_json_schema(
    numeric: NumericFields = "number",
    *,
    vat_base: bool = False,
    referenced_invoice: bool = True,
    max_lines: int = 120,
) -> dict[str, Any]:
    """JSON Schema of `RawExtraction`, written out for constrained decoding.

    Hand-written rather than generated by pydantic: no `$ref`, a fixed property order
    (the order in which the model writes), and every property required so that a
    missing value is an explicit null instead of an omission.

    The options reproduce the shapes earlier prompt versions asked for, so that their
    recorded answers stay replayable:

    - `numeric`: amounts and quantities as JSON numbers, or as text copied from the
      page. Identifiers and dates are always text.
    - `vat_base`: the taxable base on each VAT row. Models filled it with the VAT
      amount when the page printed none.
    - `referenced_invoice`: on a credit note, the invoice it cancels.
    """
    number = _NULLABLE_NUMBER if numeric == "number" else _NULLABLE_STRING
    line = {
        "type": "object",
        "properties": {
            "description": {"type": "string"},
            "quantity": number,
            "unit_price": number,
            "amount": number,
            "vat_rate": number,
        },
        "required": ["description", "quantity", "unit_price", "amount", "vat_rate"],
    }
    vat_fields = ("rate", "base", "tax") if vat_base else ("rate", "tax")
    vat_line = {
        "type": "object",
        "properties": dict.fromkeys(vat_fields, number),
        "required": list(vat_fields),
    }
    properties: dict[str, Any] = {
        "document_type": {"type": "string", "enum": ["invoice", "credit_note", "other"]},
        "invoice_number": _NULLABLE_STRING,
        "issue_date": _NULLABLE_STRING,
        "due_date": _NULLABLE_STRING,
        "currency": _NULLABLE_STRING,
        "supplier_name": _NULLABLE_STRING,
        "supplier_vat_id": _NULLABLE_STRING,
        "supplier_siret": _NULLABLE_STRING,
        "supplier_iban": _NULLABLE_STRING,
        "po_number": _NULLABLE_STRING,
        "referenced_invoice": _NULLABLE_STRING,
        "lines": {"type": "array", "items": line, "maxItems": max_lines},
        "allowance_total": number,
        "charge_total": number,
        "total_net": number,
        "vat_breakdown": {"type": "array", "items": vat_line, "maxItems": 8},
        "total_tax": number,
        "total_gross": number,
    }
    if not referenced_invoice:
        del properties["referenced_invoice"]
    return {"type": "object", "properties": properties, "required": list(properties)}
